In [3]:
#import dependencies

import pandas as pd
import numpy as np

In [1]:
# Load in file
file_path = "2019-09_2020-06.csv"

In [4]:
# Read and display the CSV with Pandas
summary_df = pd.read_csv(file_path,encoding='ISO-8859-1')
summary_df.head(5)

,ï»¿tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,327,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,Subscriber,1968,1
1,1145,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,Customer,1969,0
2,1293,2019-09-01 00:00:07.3090,2019-09-01 00:21:40.7580,3168,Central Park West & W 85 St,40.784727,-73.969617,423,W 54 St & 9 Ave,40.765849,-73.986905,15242,Customer,1969,0
3,1753,2019-09-01 00:00:08.0640,2019-09-01 00:29:21.5040,3299,E 98 St & Park Ave,40.788130,-73.952060,3160,Central Park West & W 76 St,40.778968,-73.973747,38760,Subscriber,1990,1
4,613,2019-09-01 00:00:12.8510,2019-09-01 00:10:26.1850,486,Broadway & W 29 St,40.746201,-73.988557,478,11 Ave & W 41 St,40.760301,-73.998842,32094,Subscriber,1992,1

In [6]:
#Deleting members that are over 65 years old (born before 1956)

summary_df.drop(summary_df[summary_df['birth year'] < 1956].index, inplace = True)

In [7]:
summary_df['birth year'].min()

1956

In [9]:
#Replacing Gender (0 = unknown & 1 = male & 2 = female)
summary_df.loc[(summary_df.gender == 0),'gender']='unknown'
summary_df.loc[(summary_df.gender == 1),'gender']='male'
summary_df.loc[(summary_df.gender == 2),'gender']='female'

In [11]:
summary_df.head()

,ï»¿tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,327,2019-09-01 00:00:01.9580,2019-09-01 00:05:29.3410,3733,Avenue C & E 18 St,40.730563,-73.973984,504,1 Ave & E 16 St,40.732219,-73.981656,39213,Subscriber,1968,male
1,1145,2019-09-01 00:00:04.1430,2019-09-01 00:19:09.8360,3329,Degraw St & Smith St,40.682915,-73.993182,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,21257,Customer,1969,unknown
2,1293,2019-09-01 00:00:07.3090,2019-09-01 00:21:40.7580,3168,Central Park West & W 85 St,40.784727,-73.969617,423,W 54 St & 9 Ave,40.765849,-73.986905,15242,Customer,1969,unknown
3,1753,2019-09-01 00:00:08.0640,2019-09-01 00:29:21.5040,3299,E 98 St & Park Ave,40.788130,-73.952060,3160,Central Park West & W 76 St,40.778968,-73.973747,38760,Subscriber,1990,male
4,613,2019-09-01 00:00:12.8510,2019-09-01 00:10:26.1850,486,Broadway & W 29 St,40.746201,-73.988557,478,11 Ave & W 41 St,40.760301,-73.998842,32094,Subscriber,1992,male

In [13]:
#Exporting cleaned dataframe into csv
summary_df.to_csv('Cleaned_data_2019-09_2020-06.csv', index=False)